const TGPL_PROJECT_ID = '3';
const TGPL2_PROJECT_ID = '4';

const PROJECT_TYPES = {
  POLE_SURVEY: 'POLE_SURVEY',
  TGPL_SURVEY: 'TGPL_SURVEY',
  TGPL2_SURVEY: 'TGPL2_SURVEY'
};

module.exports = {
  TGPL_PROJECT_ID,
  TGPL2_PROJECT_ID,
  PROJECT_TYPES
};
