const SURVEY_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  ISSUE_OPEN: 'ISSUE_OPEN',
  ISSUE_RESOLVED: 'ISSUE_RESOLVED',
};

const ISSUE_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  ESCALATED: 'ESCALATED',
  RESOLVED: 'RESOLVED',
};

module.exports = { SURVEY_STATUS, ISSUE_STATUS };
